export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POST = 'NEW_POST';
export const FETCH_METADATASEARCHRESULTS = 'FETCH_METADATASEARCHRESULTS';
export const FETCH_ARTICLESEARCHRESULTS = 'FETCH_ARTICLESEARCHRESULTS';