export const FETCH_MAPITEMS = 'FETCH_MAPITEMS';
export const FETCH_METADATASEARCHRESULTS = 'FETCH_METADATASEARCHRESULTS';
export const FETCH_ARTICLESEARCHRESULTS = 'FETCH_ARTICLESEARCHRESULTS';
export const FETCH_DROPDOWNSEARCHRESULTS = 'FETCH_DROPDOWNSEARCHRESULTS';